Custom push script for stable-check

diff --git a/.github/workflows/stable-check.yml b/.github/workflows/stable-check.yml
--- a/.github/workflows/stable-check.yml
+++ b/.github/workflows/stable-check.yml
@@ -1,5 +1,8 @@
 name: Check for updates
 
+permissions:
+  contents: write
+
 on:
   push:
     branches: [ main ]
@@ -55,12 +58,33 @@ jobs:
       - name: Wait
         if: ${{ github.event_name != 'pull_request' }}
         run: sleep 15m
-      - name: Run Workflow
-        uses: antaljanosbenjamin/single-commit-publish@v1.0.1
-        with:
-          github-token: ${{ secrets.WORKFLOW_TOKEN }}
-          branch: trigger/stable
-          files-and-dirs: '.github/workflows/stable-${{ matrix.crate }}.yml keys/ scripts/collect.py scripts/info.py scripts/crate-info.py scripts/misc.py scripts/docker/entrypoint.sh ${{ matrix.file }} Cross.toml'
+      - name: Run Generated Workflow
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        run: |
+          set -euxo pipefail
+
+          TEMP_DIR="$(mktemp -d)"
+
+          # Move files
+          cp '${{ matrix.file }}' 'Cross.toml' '.github/workflows/stable-${{ matrix.crate }}.yml' $TEMP_DIR
+          cp -r keys scripts $TEMP_DIR
+
+          # Commit and Push
+          pushd $TEMP_DIR
+
+          git init
+          git config user.name 'github-actions'
+          git config user.email 'github-actions@noreply.github.com'
+          git remote add origin "https://${{ github.actor }}:$GITHUB_TOKEN@github.com/${{ github.repository }}.git"
+          git checkout -b tmp
+          git add -f .
+          git commit -m "Publish crate ${{ matrix.crate }} ${{ matrix.version }} from #${{ github.run_number }}"
+          git push --force origin tmp:trigger/stable
+
+          # Cleanup
+          popd
+          rm -rf $TEMP_DIR
 
   wait:
     if: ${{ github.event_name != 'pull_request' }}
